### ISSUE TITLE
Clear Doodles Bug

### ISSUE THREAD

**Issue by 2320sharon** [dbuscombe-usgs/holodoodler#1]
After clicking the 'clear doodles' button any subsequent doodles that get drawn are erased from the canvas whenever the user changes the label.

No error messages appear in the console and this only happens sometimes. It doesn't only occur in grey imagery it has also happened in colored images as well.

![weird holodoodlerbug_after_clear_doodles](https://user-images.githubusercontent.com/61564689/178077457-0e0f8a25-40fc-46a6-909c-25c66289a659.gif)

**Comment by venuswku** [comment]
I've been having this bug after getting the segmentation results and clearing the doodles! I'll be looking into this soon.
I also had to click the `Clear doodles` button twice to get rid of all the old doodles but I can open another issue for that.
